title: France Religious Composition ABM
description: NetLogo ABM scenarios of religious composition change in France using migration and fertility assumptions.
url: https://nikolailen.github.io
baseurl: /france-religious-composition-abm
markdown: kramdown
